name: Terraform apply
on: [workflow_run]
jobs:
  Terraform-Init:
    runs-on: self-hosted
    steps:
      - name: Check out repo code
        uses: actions/checkout@v4
      - name: List files in the repo
        run: |
          terraform init -backend-config=env-dev/state.tfvars